# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tULBrMAvCokBy-ZLiMbAcBl90iRDE6BJ
"""

import requests

data = requests.get('https://raw.githubusercontent.com/wez/wezterm/f535c5bdc092c82db1b939c82babf98a2436c456/docs/colorschemes/data.json').json()
new_data = {}

for colorscheme in data:
    name       = colorscheme['metadata']['name']
    background = colorscheme['colors']['background']
    foreground = colorscheme['colors']['foreground']
    midground  = colorscheme['colors']['ansi'][4]
    new_data[name] = {
        'background': background,
        'midground' : midground,
        'foreground': foreground
    }

import json

with open('wezterm_colors.json', 'w') as file:
    file.write(json.dumps(new_data))

